# Generated by Django 4.1.3 on 2022-11-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonies',
            new_name='Testimony',
        ),
    ]
