# Generated by Django 4.1.3 on 2022-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_testimonies_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
