# Generated by Django 4.1.3 on 2022-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimony_date_published_testimony_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='testimony',
            new_name='testimony_text',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
